# Generated by Django 5.0.6 on 2024-08-09 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tryon", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="weight",
            new_name="chest_size",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="captured_image",
            field=models.TextField(blank=True, null=True),
        ),
    ]
